baseURL = "https://ghomist.github.io/"

title = "Ghomist 个人随笔"
theme = "blowfish"

languageCode = "zh-cn"
enableEmoji = true
enableGitInfo = true
hasCJKLanguage = true
defaultContentLanguage = "zh-cn"

[taxonomies]
tag = "tags"
series = "series"
category = "categories"
