baseURL = "https://ghomist.github.io/"

# https://blowfish.page/docs/configuration/#language-and-i18n
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"

title = "Ghomist 个人随笔"
theme = "blowfish"
