# [[main / footer]]
# name =
# pageRef = link to the dir
# weight = <number> sort labels
# pre = <icon>
# url = <url>
# identifier = <id-string>

[[main]]
name = "文章"
pageRef = "posts"
weight = 1

[[main]]
name = "随笔"
pageRef = "arts"
weight = 2

[[main]]
pre = "github"
name = "Blog 仓库"
url = "https://github.com/Ghomist/blog"
weight = 10

# [[footer]]
# name = "Privacy"
# url = "https://external-link"
